version: "3.8"

services:

  postgres:
    image: postgres:16
    container_name: temporal-postgres
    restart: always
    environment:
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    ports:
      - "5432:5432"

  temporal:
    image: temporalio/auto-setup:1.29
    container_name: temporal
    restart: always
    depends_on:
      - postgres
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: temporal-postgres
      TEMPORAL_NAMESPACE: default
      TEMPORAL_TLS_SERVER_CERT: /etc/temporal/certs/server.crt
      TEMPORAL_TLS_SERVER_KEY: /etc/temporal/certs/server.key
      TEMPORAL_TLS_SERVER_CA_CERT: /etc/temporal/certs/ca.crt

      TEMPORAL_TLS_FRONTEND_CERT: /etc/temporal/certs/server.crt
      TEMPORAL_TLS_FRONTEND_KEY: /etc/temporal/certs/server.key
      TEMPORAL_TLS_CLIENT1_CA_CERT: /etc/temporal/certs/ca.crt

      TEMPORAL_TLS_FRONTEND_SERVER_NAME: temporal
      TEMPORAL_TLS_INTERNODE_SERVER_NAME: temporal

    volumes:
      - ../temporal-certs:/etc/temporal/certs
    ports:
      - "7233:7233"


  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    restart: always
    depends_on:
      - temporal
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_TLS_CA: /etc/temporal/certs/ca.crt
      TEMPORAL_TLS_CERT: /etc/temporal/certs/client.crt      # ← ADD
      TEMPORAL_TLS_KEY: /etc/temporal/certs/client.key       # ← ADD
      TEMPORAL_TLS_ENABLE_HOST_VERIFICATION: "true"
      TEMPORAL_NAMESPACE: default 
    ports:
      - "8080:8080"
    volumes:
      - ../temporal-certs:/etc/temporal/certs
